## 1. 데이터 스케일링 ( Scaling )

- 데이터 특성 ( Feature)간의 범위를 통일시켜서 모델이 데이터를 잘 이해하고 학습할 수 있도록 하는 방법
- 머신러닝 전처리 과정에서 상당히 중요한 방법
- sklearn 라이브러리 사용 . preprocessing
- 여러 특성이 다양한 단위와 범위를 가질때 데이터 범위를 일정한 범위로 변환하는 전처리 과정
- 정규화 ( Normaliztion )  , 표준화 ( Standard ) 로 구분

### 1) 정규화 

- 데이터의 각 특성의 최소값과 최대값을 이용해서 0 ~ 1 사이의 범위로 조정
- 최소값은 0, 촤대값은 1 로 맞추어서 변환
- 데이터 값들 간의 상대적 거리는 그대로 유지하면서 , 모든 변수가 동일한 척도를 가지게 만드는 방법
- sklearn : minmaxScaler , robustScaler 

### 2) 표준화

- 평균이 0이고 , 표준편차가 1이 되도록 변환 시키는 방법
- 이 방법은 최소값과 최대값을 제한하지 않음
- μ는 평균, σ는 표준 편차
- 각 데이터 변수에서 평균을 뺀 다음 표준편차로 나눈 스케일링 방법
- sklearn : standardScaler , z-score

In [2]:
from sklearn.preprocessing import StandardScaler 
import numpy as np

In [6]:
data = np.array([[10,2.7,3.6],
                [-100,0,1],
               [200,12.5,-0.5]])
data

array([[  10. ,    2.7,    3.6],
       [-100. ,    0. ,    1. ],
       [ 200. ,   12.5,   -0.5]])

In [14]:
scaler = StandardScaler()

In [16]:
# Standard 
data_standardized = scaler.fit_transform(data)
data_standardized

array([[-0.21519688, -0.44067938,  1.31855024],
       [-1.102884  , -0.94342629, -0.2164784 ],
       [ 1.31808087,  1.38410567, -1.10207185]])

In [17]:
from sklearn.preprocessing import RobustScaler 

In [18]:
scaler = RobustScaler()

In [26]:
''' 
RobustScaler : 평균과 표준편차를 사용하지 않음 => 대신 IQR 값을 사용 ( 데이터의 가운데 50% 범위)

스케일로 변환값 = (원래값 - 중앙값 ) / IQR 
- 0 ~ 1사이의 범위로 바꾸는 정규화 도구가 아니라 중앙값과 IQR 값을 기준으로 값을 재조정하는 스케일러 
- if 0 ~ 1사이의 범위로 바꾸고 싶을 경우라면 , MinMaxScaler를 사용 
- MinMaxScaler : 최소값, 최대값 / 범위는 0 ~ 1 
- StandardScaler : 평균 , 표준편차 / 범위는 0 ~ 1 이 아님
- RobustScaler : 중앙값 , IQR / 범위는 0 ~ 1 이 아니다. 

'''
data_robusterized = scaler.fit_transform(data)
data_robusterized

array([[ 0.        ,  0.        ,  1.26829268],
       [-0.73333333, -0.432     ,  0.        ],
       [ 1.26666667,  1.568     , -0.73170732]])

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [28]:
scaler = MinMaxScaler()

In [30]:
data_normalized = scaler.fit_transform(data)
data_normalized 

array([[0.36666667, 0.216     , 1.        ],
       [0.        , 0.        , 0.36585366],
       [1.        , 1.        , 0.        ]])