Numpy = Numerical Python 

수를 다루는 라이브러리

- 라이브러리 - 모듈 - 함수 

- 음식 - 한식 - 국수

라이브러리를 호출하는것을 임포트 


- Numpy 배열은 n-array를 형성해서 모양을 구성 
- 인덱싱 , 슬라이싱 , 브로드캐스팅으로 빠르게 데이터 연산하여 처리
- 배열 통계(합 , 평균 , 표준편차 ) , 축(axis)
- Numpy는 배열 연산 기능을 지원하는 특화된 라이브러리
- tensorflow와 조화가 좋음
- 생성할때 크기가 결정됨 



- 라이브러리 import 하는 방식
  - import 라이브러리명 as 별칭(라이브러리를 호칭하는 별칭 또는 약칭)
  - from ~~~ . ~~~~ import 라이브러리명
  -  ex) import numpy as np , import pandas as pd 

In [2]:
import numpy as np

In [4]:
list = [1,2,3]
array = np.array(list)

array

array([1, 2, 3])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [13]:
np.random.rand()

0.036139747853680904

In [14]:
np.random.rand(2,3)

array([[0.76376306, 0.63432601, 0.40419423],
       [0.09888056, 0.59080589, 0.39669954]])

- random 모듈의 주요 함수
  
1) rand : 균등분포에서의 랜덤 추출
2) raidnt : 주어진 범위안에서 핸덤 추출
3) rand : 표준 정규분포에서 랜덤 추출
            - 표준 정규분초 : 평균 0 , 표준편차 1
4) normal : 정규분포에서 랜덤 추출
5) seed : 랜덤값 생성기에서 시드(고정값)를 생성
6) shuffle : 리스트나 배열의 순서를 섞음 


In [18]:
array2 = np.arange(16)
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
array2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
array2.shape

(16,)

In [22]:
array2.dtype

dtype('int64')

In [24]:
array3 = array2.astype(float)
array3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [25]:
array3.dtype

dtype('float64')

In [27]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
print(arr[-1])

15


In [32]:
print(arr[5:8])

[5 6 7]


In [34]:
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [37]:
arr[6:8] = 200 , 201
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [40]:
arr2 = np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
arr2[1,1]

np.int64(5)

In [43]:
arr2[0:2,2:4]

array([[2, 3],
       [6, 7]])

In [44]:
arr2[-4:-2,-2: ]

array([[2, 3],
       [6, 7]])

In [45]:
arr2[:2,2:]

array([[2, 3],
       [6, 7]])

In [46]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
scores_arr = np.array(scores)

scores_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [47]:
scores_arr >= 90 

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [48]:
scores_arr[scores_arr >= 90 ] 

array([90, 95, 90])

In [50]:
scores_arr[scores_arr >= 90 ]  = 100
scores_arr

array([ 80, 100,  70,  65,  85, 100, 100,  80,  75,  80])

In [56]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [57]:
arr * 2 

array([2, 4, 6, 8])

In [58]:
arr2 = np.arange(5,9)
arr2

array([5, 6, 7, 8])

In [59]:
arr + arr2

array([ 6,  8, 10, 12])

In [60]:
arr * arr2

array([ 5, 12, 21, 32])

In [62]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [63]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [64]:
np.add(arr,arr2)

array([ 6,  8, 10, 12])

In [65]:
np.sum(arr)

np.int64(10)

In [66]:
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [67]:
np.mean(arr)

np.float64(2.5)

In [68]:
np.var(arr)

np.float64(1.25)

In [ ]:
# standard deviation = 표준편차 = std
np.std(arr)

np.float64(1.118033988749895)

In [70]:
np.max(arr)

np.int64(4)

In [71]:
np.min(arr)

np.int64(1)

In [74]:
np.argmin(arr)

np.int64(0)

In [75]:
np.argmax(arr)

np.int64(3)

In [77]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr.T 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [81]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])